### ISSUE TITLE
_InactiveRpcError

### ISSUE THREAD

**Issue by E-B-Manohar** [notAI-tech/deepsegment#42]
WARNING:root:Batch input strings for faster inference.
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
<ipython-input-45-923460d99b84> in <module>()
----> 1 segmenter.segment('I am Batman i live in gotham')

3 frames
/usr/local/lib/python3.6/dist-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    727             return state.response
    728     else:
--> 729         raise _InactiveRpcError(state)
    730 
    731 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1613662201.237905180","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1613662201.237902717","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>

https://colab.research.google.com/drive/1XrUCHamureKc0r1Sl4GA7QG9FsHv7ayH?usp=sharing

**Comment by bedapudi6788** [comment]
What are your tensorflow and keras versions?

**Comment by E-B-Manohar** [comment]
> What are your tensorflow and keras versions?

@bedapudi6788 , I have provided the colab output above, I am sharing again the colab notebook, it contains all the requirements and the libraries' version;
please look into it.
Thanks in advance

https://colab.research.google.com/drive/1XrUCHamureKc0r1Sl4GA7QG9FsHv7ayH?usp=sharing

**Comment by bedapudi6788** [comment]
**There is a reason issue template exists.**


<img width="984" alt="Screenshot 2021-02-19 at 1 50 01 PM" src="https://user-images.githubusercontent.com/15898654/108477553-5ecde480-72b9-11eb-9e5e-c166d172c2a6.png">

**Comment by E-B-Manohar** [comment]
> @E-B-Manohar **There is a reason issue template exists.**
> 
> <img alt="Screenshot 2021-02-19 at 1 59 02 PM" width="724" src="https://user-images.githubusercontent.com/15898654/108478529-a0ab5a80-72ba-11eb-8bed-de4866a224c9.png">

Please Access the Notebook from: 
https://github.com/E-B-Manohar/Public-Shares/blob/main/Untitled5.ipynb

**Comment by bedapudi6788** [comment]
You are trying to use it with tf serving, but don't have tf serving docker image running anywhere!

Also, I am not going to answer any further questions in this issue. Learn to follow the issue template and specify what you are exactly trying to do and what issues you are facing clearly.

You can't expect people to go through your notebooks and debug for you.

**Comment by E-B-Manohar** [comment]
> You are trying to use it with tf serving, but don't have tf serving docker image running anywhere!
> 
> Also, I am not going to answer any further questions in this issue. Learn to follow the issue template and specify what you are exactly trying to do and what issues you are facing clearly.
> 
> You can't expect people to go through your notebooks and debug for you.

Please don't be rude at my issue, either answer it or don't. You might be created this repo but if can't answer professionally, hire someone who can do that for you or change ownership to someone who is capable.

**Comment by bedapudi6788** [comment]
I am not the rude person here. You didn't follow the issue template even after I asked you to. You are expecting me to go through some random colab/ipynb notebook to figure out what's the issue. I said I am not going to do that.

> You might be created this repo but if can't answer professionally, hire someone who can do that for you or change ownership to someone who is capable.

Feel free to not use it.

**Comment by E-B-Manohar** [comment]
> You are trying to use it with tf serving, but don't have tf serving docker image running anywhere!

I'm trying to run it on colab. Great product BTW. New to issue templates, learning is in to do..
Tank You

**Comment by E-B-Manohar** [comment]
> You are trying to use it with tf serving, but don't have tf serving docker image running anywhere! 
> You can't expect people to go through your notebooks and debug for you.

Well, You pointed out the error but did **not specified how to resolve it programmatically still** and **_complaining rudly about not using your custom issue template._** Though I mentioned the issue name, error output, and where that error occured in the code with the ipynb for any future need in solving for this  error.

I solved it with help of other professtionals;

Tank You

**Comment by bedapudi6788** [comment]
Stop being an entitled ass.

> Well, You pointed out the error but did not specified how to resolve it programmatically 

The readme clearly shows you need to start the docker server to be able to use with tensorflow_serving.
<img width="902" alt="Screenshot 2021-02-19 at 7 56 32 PM" src="https://user-images.githubusercontent.com/15898654/108516712-91dd9b80-72ec-11eb-849f-0a1a5df037c2.png">


If you can't/ don't even the readme, nobody is going to help you.

> complaining rudly about not using your custom issue template.

WOW! Again, stop being an entitled ass. It is my repo. Either follow the issue temnplate if you want help, or simply piss off.
I don't owe you anything.

> I solved it with help of other professtionals;

If you need "professional" help to copy paste 3 obvious commands from a readme, I pity you.


PS: If you believe you are in the right, why did you delete your multiple previous comments. (In one, you tell me to hire professionals to help idiots like you!)

**Comment by E-B-Manohar** [comment]
> Stop being an entitled ass.
> 
> > Well, You pointed out the error but did not specified how to resolve it programmatically
> 
> The readme clearly shows you need to start the docker server to be able to use with tensorflow_serving.
> <img alt="Screenshot 2021-02-19 at 7 56 32 PM" width="902" src="https://user-images.githubusercontent.com/15898654/108516712-91dd9b80-72ec-11eb-849f-0a1a5df037c2.png">
> 
> If you can't/ don't even the readme, nobody is going to help you.
> 
> > complaining rudly about not using your custom issue template.
> 
> WOW! Again, stop being an entitled ass. It is my repo. Either follow the issue temnplate if you want help, or simply piss off.
> I don't owe you anything.
> 
> > I solved it with help of other professtionals;
> 
> If you need "professional" help to copy paste 3 obvious commands from a readme, I pity you.
> 
> PS: If you believe you are in the right, why did you delete your multiple previous comments. (In one, you tell me to hire professionals to help idiots like you!)

I deleted my git repo public share link from previous replies only.
And I mentioned the problem is raised in "Google's colab" but you still sending home page tutorial screenshot for shell usage. Please use issue resolving section with non-abusive vocabulary; GitHub is dignified community.

**Comment by bedapudi6788** [comment]
> I deleted my git repo public share link from previous replies only.

Right.. so, the multiple other comments telling me to hire some maintainer and (weirdly) thanking me in one comment and a couple of other somewhat weird messages all just magically disappeared?

**Comment by bedapudi6788** [comment]
> Please use issue resolving section with non-abusive vocabulary; GitHub is dignified community.


It ain't that dignified a place, if entitled idiots like you are present.
